### PR TITLE
Support for IAM Multiple Zone Availability

### PR DESCRIPTION
**Pull request by milujogi**
GH : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61622 
To enforce multi zone deploy, IAM needs to add configuration for podAntiAffinity with `topologyKey: topology.kubernetes.io/zone `

### CODE REVIEW

**Comment by Tirumalavasa** [comment]
> To enforce multi zone deploy, IAM needs to add configuration for podAntiAffinity with `topologyKey: topology.kubernetes.io/zone `

@milujogi , can you please tag the Gh work-item here

**Comment by milujogi** [comment]
@Tirumalavasa Added the GH issue link in the description.

**Review by rashmi43 — APPROVED** [review]

**Review by Tirumalavasa — APPROVED** [review]
/lgtm

**Pull request merged**
