### PR TITLE
Updated latest image sha digest for identity-manager.

### PR DESCRIPTION
**Pull request by pnpavan25**
Updated latest image sha digest for identity-manager.

### CODE REVIEW

**Comment by pnpavan25** [comment]
@here Travis build link for image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/40641592#L322

**Review by znhafeez — APPROVED** [review]
lgtm

**Comment by pnpavan25** [comment]
@here Updated PR with identity-provider image. Here is the travis build link for image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/40644902#L288

**Comment by znhafeez** [comment]
looks good!

**Review by znhafeez — APPROVED** [review]

**Pull request merged**
