### PR TITLE
updating sha for identity-manager

### PR DESCRIPTION
**Pull request by znhafeez**
https://github.ibm.com/IBMPrivateCloud/platform-identity-mgmt/pull/598
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/38017156#L306

### CODE REVIEW

**Comment by crescent1consult** [comment]
Lgtm

**Comment by rashmi43** [comment]
Lgtm

**Comment by znhafeez** [comment]
@rashmi43 can you add the `lgtm` label or click the approve button, please?

**Review by yannizhang2019 — APPROVED** [review]
lgtm

**Pull request merged**
