### PR TITLE
Update for ingress api version update 

### PR DESCRIPTION
**Pull request by yannizhang2019**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46010

OCP new version will include kubernetes 1.22 that has ingress API version change to k8s.io/api/networking/v1, and old version will not be supported.

This branch has the code to move to k8s.io/api/networking/v1. To do that, we need to update SDK operator version, and several other library versions due to incompatibility between different library versions, which results in significant code changes. To minimize the impact, this prototype change to use klog library. 

The code was compiled but need further evaluation and testing.

### CODE REVIEW

**Comment by yannizhang2019** [comment]
Errors in the build log 
```
pkg/controller/policycontroller/policycontroller_controller.go:143:3: undefined: reqLogger
# github.com/IBM/ibm-iam-operator/pkg/controller/secretwatcher
pkg/controller/secretwatcher/secretwatcher_controller.go:143:3: undefined: reqLogger
```
which do not match the code https://github.com/IBM/ibm-iam-operator/blob/ingress-apiversion-change/pkg/controller/policycontroller/policycontroller_controller.go#L143

https://github.com/IBM/ibm-iam-operator/blob/ingress-apiversion-change/pkg/controller/secretwatcher/secretwatcher_controller.go#L143

**Comment by rashmi43** [comment]
@yannizhang2019 I deployed your changes,  this is the error I get.
```
I0604 10:54:11.335376       1 authentication_controller.go:197] Reconciling Authentication
I0604 10:54:11.335605       1 ingress.go:51] Creating a new IngressIngress.Namespaceibm-common-servicesIngress.Nameapi-key
E0604 10:54:11.339444       1 ingress.go:54] Ingress.extensions "api-key" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specifiedFailed to create new IngressIngress.Namespaceibm-common-servicesIngress.Nameapi-key
I0604 10:54:12.534876       1 authentication_controller.go:197] Reconciling Authentication
I0604 10:54:12.535081       1 ingress.go:51] Creating a new IngressIngress.Namespaceibm-common-servicesIngress.Nameapi-key
E0604 10:54:12.539059       1 ingress.go:54] Ingress.extensions "api-key" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specifiedFailed to create new IngressIngress.Namespaceibm-common-servicesIngress.Nameapi-key

**Review by cwangVT — APPROVED** [review]

**Pull request merged**
