### PR TITLE
Handle console url for registration json based on port 443 #55171

### PR DESCRIPTION
**Pull request by PRTamilanban**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55171

### CODE REVIEW

**Comment by ujjwalchk-it** [comment]
Hi @PRTamilanban Can you please test the below scenarios and attach the result ?

1. Test in OCP cluster - 

- [ ] Registration.json is properly updated 
- [ ] OauthClient registration is properly done (verify in mongo)
- [ ] CP console and CPD console login should work fine - validate the redirectURL for /authorise call
- [ ] Test/validate against fresh install
- [ ] Test/validate against upgrade

- [ ] Check if we can mock the hostname in the ingress configmap by spinning down ingress operator
- [ ] verify adding different ports/with 443 - registration json updated as expected

2. Test in CNCF cluster / EKS env -
(May need SERT help)

- [ ] Verify with port 443 - registration json updated as expected (2 patterns of entry should be created)
- [ ] Login to CP Console and CPD console still should work (which doesn't work today)
- [ ] Verify with different port apart from 443 - registration json updated as expected (1 pattern of entry should be created)
- [ ] Login to CP Console and CPD console still should work
- [ ] Verify with no port - registration json updated as expected (1 pattern of entry should be created without port)
- [ ] Login to CP Console and CPD console still should work

**Comment by PRTamilanban** [comment]
I have tested the image in my ocp fyre cluster it is woking as expected.
Below test cases
In management-ingress-info config map has 

**Usecase 1:** 
_url with 443 port_ ( MANAGEMENT_INGRESS_ROUTE_HOST: '_**cp-console.apps.tamil-dev.cp.fyre.ibm.com:443**_')

1.Registration Json is populated properly
```
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator % oc get cm registration-json -o yaml                 
apiVersion: v1
data:
  platform-oidc-registration.json: |
    {
       "token_endpoint_auth_method":"client_secret_basic",
       "client_id": "mhlw2d46l25rkvxgt7856sru2lyqh7k6",
       "client_secret": "wb3hr6toqp00a1qdgn9lpbw67d4p3y3g",
       "scope":"openid profile email",
       "grant_types":[
          "authorization_code",
          "client_credentials",
          "password",
          "implicit",
          "refresh_token",
          "urn:ietf:params:oauth:grant-type:jwt-bearer"
       ],
       "response_types":[
          "code",
          "token",
          "id_token token"
       ],
       "application_type":"web",
       "subject_type":"public",
       "post_logout_redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:443/console/logout"],
       "preauthorized_scope":"openid profile email general",
       "introspect_tokens":true,
       "trusted_uri_prefixes":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:443"],
       "redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com/auth/liberty/callback","https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:443/auth/liberty/callback","https://127.0.0.1:443/idauth/oidc/endpoint/OP"]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T08:54:14Z"
  labels:
    app: auth-idp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:platform-oidc-registration.json: {}
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"03bb05f5-b825-49a5-9893-c26cc4029ced"}: {}
    manager: ibm-iam-operator
    operation: Update
    time: "2022-10-19T08:54:14Z"
  name: registration-json
  namespace: ibm-common-services
  ownerReferences:
  - apiVersion: operator.ibm.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Authentication
    name: example-authentication
    uid: 03bb05f5-b825-49a5-9893-c26cc4029ced
  resourceVersion: "5858883"
  uid: 25744657-b409-47b8-9592-08b7d8982e52
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator % 
```
2. OauthClient registration is properly updated in mongo
```
rs0:PRIMARY> db.OauthClient.find()
{ "_id" : ObjectId("6350e7e39087f845af53e212"), "CLIENTID" : "jvjxtvqtop8vjesfsejqhxzksy2nxqhp", "PROVIDERID" : "Oauth", "CLIENTSECRET" : "{xor}Ji4mbG1uKDYuMW49MzclOS9rKSVvLDQlKG07MD4rLTA=", "DISPLAYNAME" : "jvjxtvqtop8vjesfsejqhxzksy2nxqhp", "ENABLED" : true, "METADATA" : "{\"client_id_issued_at\":1666246627,\"registration_client_uri\":\"https://platform-auth-service:9443/oidc/endpoint/OP/registration/jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"client_secret_expires_at\":0,\"token_endpoint_auth_method\":\"client_secret_basic\",\"scope\":\"openid profile email\",\"grant_types\":[\"authorization_code\",\"client_credentials\",\"password\",\"implicit\",\"refresh_token\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\"],\"response_types\":[\"code\",\"token\",\"id_token token\"],\"application_type\":\"web\",\"subject_type\":\"public\",\"post_logout_redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/console/logout\"],\"preauthorized_scope\":\"openid profile email general\",\"introspect_tokens\":true,\"trusted_uri_prefixes\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/\"],\"resource_ids\":[],\"functional_user_groupIds\":[],\"proofKeyForCodeExchange\":false,\"publicClient\":false,\"appPasswordAllowed\":false,\"appTokenAllowed\":false,\"hash_itr\":0,\"hash_len\":0,\"client_id\":\"jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"client_secret\":\"{xor}Ji4mbG1uKDYuMW49MzclOS9rKSVvLDQlKG07MD4rLTA=\",\"client_name\":\"jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com/auth/liberty/callback\",\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/auth/liberty/callback\",\"https://127.0.0.1:443/idauth/oidc/endpoint/OP\"],\"allow_regexp_redirects\":false}" }
rs0:PRIMARY>
```
3.I have tried accessing cp console,cpd console and ldap login also working as expected.


**Usecase 2:** 
_url with 8443_ port ( MANAGEMENT_INGRESS_ROUTE_HOST: '**_cp-console.apps.tamil-dev.cp.fyre.ibm.com:8443_**')

1.Registration Json is populated properly

```
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator % oc get cm registration-json -o yaml
apiVersion: v1
data:
  platform-oidc-registration.json: |
    {
       "token_endpoint_auth_method":"client_secret_basic",
       "client_id": "flo7jo8jf2mumqxbgvznm353hhou43em",
       "client_secret": "stp5fkrt8nlzrbuwzfvpr0iau4bmelq2",
       "scope":"openid profile email",
       "grant_types":[
          "authorization_code",
          "client_credentials",
          "password",
          "implicit",
          "refresh_token",
          "urn:ietf:params:oauth:grant-type:jwt-bearer"
       ],
       "response_types":[
          "code",
          "token",
          "id_token token"
       ],
       "application_type":"web",
       "subject_type":"public",
       "post_logout_redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:8443/console/logout"],
       "preauthorized_scope":"openid profile email general",
       "introspect_tokens":true,
       "trusted_uri_prefixes":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:8443"],
       "redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com:8443/auth/liberty/callback","https://127.0.0.1:443/idauth/oidc/endpoint/OP"]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T09:54:06Z"
  labels:
    app: auth-idp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:platform-oidc-registration.json: {}
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"03bb05f5-b825-49a5-9893-c26cc4029ced"}: {}
    manager: ibm-iam-operator
    operation: Update
    time: "2022-10-19T09:54:06Z"
  name: registration-json
  namespace: ibm-common-services
  ownerReferences:
  - apiVersion: operator.ibm.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Authentication
    name: example-authentication
    uid: 03bb05f5-b825-49a5-9893-c26cc4029ced
  resourceVersion: "5894677"
  uid: f8e91936-5fed-4404-92d2-2b6d8b10dfe5
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator %
```
2. OauthClient registration is properly updated in mongo
```
rs0:PRIMARY> db.OauthClient.find()
{ "_id" : ObjectId("635105930ee7b314ce876c0f"), "CLIENTID" : "ylbd5cmqev23z2hbzp6tb9muwyjns35m", "PROVIDERID" : "Oauth", "CLIENTSECRET" : "{xor}LiYyNjppayUnMjIyOChuOD1pZ28nKyg8Jzg7MTA2Zyw=", "DISPLAYNAME" : "ylbd5cmqev23z2hbzp6tb9muwyjns35m", "ENABLED" : true, "METADATA" : "{\"client_id_issued_at\":1666254227,\"registration_client_uri\":\"https://platform-auth-service:9443/oidc/endpoint/OP/registration/ylbd5cmqev23z2hbzp6tb9muwyjns35m\",\"client_secret_expires_at\":0,\"token_endpoint_auth_method\":\"client_secret_basic\",\"scope\":\"openid profile email\",\"grant_types\":[\"authorization_code\",\"client_credentials\",\"password\",\"implicit\",\"refresh_token\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\"],\"response_types\":[\"code\",\"token\",\"id_token token\"],\"application_type\":\"web\",\"subject_type\":\"public\",\"post_logout_redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:8443/console/logout\"],\"preauthorized_scope\":\"openid profile email general\",\"introspect_tokens\":true,\"trusted_uri_prefixes\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:8443/\"],\"resource_ids\":[],\"functional_user_groupIds\":[],\"proofKeyForCodeExchange\":false,\"publicClient\":false,\"appPasswordAllowed\":false,\"appTokenAllowed\":false,\"hash_itr\":0,\"hash_len\":0,\"client_id\":\"ylbd5cmqev23z2hbzp6tb9muwyjns35m\",\"client_secret\":\"{xor}LiYyNjppayUnMjIyOChuOD1pZ28nKyg8Jzg7MTA2Zyw=\",\"client_name\":\"ylbd5cmqev23z2hbzp6tb9muwyjns35m\",\"redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:8443/auth/liberty/callback\",\"https://127.0.0.1:443/idauth/oidc/endpoint/OP\"],\"allow_regexp_redirects\":false}" }
rs0:PRIMARY>
```

3.I have tried accessing cp console,cpd console and ldap login 
 It is not accessible because for testing purpose I have manully updated 8443 in management-ingress-info configmap by downscaling ingress operator to check above db and registration is properly updated.
 When I hit the cp ,cpd url im getting below eroor message
 `CWOAU0062E: The OAuth service provider could not redirect the request because the redirect URI was not valid. Contact your system administrator to resolve the problem`.
 Which is valid and expected output
 
 **Usecase 3:** 
_url with out port_ ( MANAGEMENT_INGRESS_ROUTE_HOST: '**_cp-console.apps.tamil-dev.cp.fyre.ibm.com_**')
1.Registration Json is populated properly

```
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator % oc get cm registration-json -o yaml
apiVersion: v1
data:
  platform-oidc-registration.json: |
    {
       "token_endpoint_auth_method":"client_secret_basic",
       "client_id": "3pzse6y350b3ucoydsu5qvt6ptb7nwo1",
       "client_secret": "piyxe6iafuy7zwuf3d4j1fdh77sndyco",
       "scope":"openid profile email",
       "grant_types":[
          "authorization_code",
          "client_credentials",
          "password",
          "implicit",
          "refresh_token",
          "urn:ietf:params:oauth:grant-type:jwt-bearer"
       ],
       "response_types":[
          "code",
          "token",
          "id_token token"
       ],
       "application_type":"web",
       "subject_type":"public",
       "post_logout_redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com/console/logout"],
       "preauthorized_scope":"openid profile email general",
       "introspect_tokens":true,
       "trusted_uri_prefixes":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com"],
       "redirect_uris":["https://cp-console.apps.tamil-dev.cp.fyre.ibm.com/auth/liberty/callback","https://127.0.0.1:443/idauth/oidc/endpoint/OP"]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T09:57:04Z"
  labels:
    app: auth-idp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:platform-oidc-registration.json: {}
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"03bb05f5-b825-49a5-9893-c26cc4029ced"}: {}
    manager: ibm-iam-operator
    operation: Update
    time: "2022-10-19T09:57:04Z"
  name: registration-json
  namespace: ibm-common-services
  ownerReferences:
  - apiVersion: operator.ibm.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Authentication
    name: example-authentication
    uid: 03bb05f5-b825-49a5-9893-c26cc4029ced
  resourceVersion: "5896926"
  uid: 08429a8f-e499-4042-8e46-bea8cac90b68
tamilanban@Tamilanbans-MacBook-Pro ibm-iam-operator % 
```
2. OauthClient registration is properly updated in mongo

```
rs0:PRIMARY> db.OauthClient.find()
{ "_id" : ObjectId("6350e7e39087f845af53e212"), "CLIENTID" : "jvjxtvqtop8vjesfsejqhxzksy2nxqhp", "PROVIDERID" : "Oauth", "CLIENTSECRET" : "{xor}Ji4mbG1uKDYuMW49MzclOS9rKSVvLDQlKG07MD4rLTA=", "DISPLAYNAME" : "jvjxtvqtop8vjesfsejqhxzksy2nxqhp", "ENABLED" : true, "METADATA" : "{\"client_id_issued_at\":1666246627,\"registration_client_uri\":\"https://platform-auth-service:9443/oidc/endpoint/OP/registration/jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"client_secret_expires_at\":0,\"token_endpoint_auth_method\":\"client_secret_basic\",\"scope\":\"openid profile email\",\"grant_types\":[\"authorization_code\",\"client_credentials\",\"password\",\"implicit\",\"refresh_token\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\"],\"response_types\":[\"code\",\"token\",\"id_token token\"],\"application_type\":\"web\",\"subject_type\":\"public\",\"post_logout_redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/console/logout\"],\"preauthorized_scope\":\"openid profile email general\",\"introspect_tokens\":true,\"trusted_uri_prefixes\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/\"],\"resource_ids\":[],\"functional_user_groupIds\":[],\"proofKeyForCodeExchange\":false,\"publicClient\":false,\"appPasswordAllowed\":false,\"appTokenAllowed\":false,\"hash_itr\":0,\"hash_len\":0,\"client_id\":\"jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"client_secret\":\"{xor}Ji4mbG1uKDYuMW49MzclOS9rKSVvLDQlKG07MD4rLTA=\",\"client_name\":\"jvjxtvqtop8vjesfsejqhxzksy2nxqhp\",\"redirect_uris\":[\"https://cp-console.apps.corns.cp.fyre.ibm.com/auth/liberty/callback\",\"https://cp-console.apps.corns.cp.fyre.ibm.com:443/auth/liberty/callback\",\"https://127.0.0.1:443/idauth/oidc/endpoint/OP\"],\"allow_regexp_redirects\":false}" }
```
3.I have tried accessing cp console,cpd console and ldap login also working as expected.

**Comment by PRTamilanban** [comment]
I have tested the previous comment usecase in CNCF cluster as well . Its working as expected.
**Usecase 1:**
url with 31573 port ( MANAGEMENT_INGRESS_ROUTE_HOST: 'cp-console.cncf-test4-master.fyre.ibm.com:31573')
```
root@cncf-test4-master:~# kubectl get cm management-ingress-info -oyaml |grep -i "MANAGEMENT_INGRESS_ROUTE_HOST"
  MANAGEMENT_INGRESS_ROUTE_HOST: cp-console.cncf-test4-master.fyre.ibm.com:31573
root@cncf-test4-master:~# 
```

**_1.Registration Json is populated properly_**

```
root@cncf-test4-master:~# kubectl get cm registration-json -o yaml
apiVersion: v1
data:
  platform-oidc-registration.json: |
    {
       "token_endpoint_auth_method":"client_secret_basic",
       "client_id": "g0jhtxt224e9bvleur8erbygs1ksuv9e",
       "client_secret": "cfr90zxlx8shocagp8caf3g0npm84vje",
       "scope":"openid profile email",
       "grant_types":[
          "authorization_code",
          "client_credentials",
          "password",
          "implicit",
          "refresh_token",
          "urn:ietf:params:oauth:grant-type:jwt-bearer"
       ],
       "response_types":[
          "code",
          "token",
          "id_token token"
       ],
       "application_type":"web",
       "subject_type":"public",
       "post_logout_redirect_uris":["https://cp-console.cncf-test4-master.fyre.ibm.com:31573/console/logout"],
       "preauthorized_scope":"openid profile email general",
       "introspect_tokens":true,
       "trusted_uri_prefixes":["https://cp-console.cncf-test4-master.fyre.ibm.com:31573"],
       "redirect_uris":["https://cp-console.cncf-test4-master.fyre.ibm.com:31573/auth/liberty/callback","https://127.0.0.1:443/idauth/oidc/endpoint/OP"]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-04T14:55:18Z"
  labels:
    app: auth-idp
  name: registration-json
  namespace: ibm-common-services
  ownerReferences:
  - apiVersion: operator.ibm.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Authentication
    name: example-authentication
    uid: f0124b00-a026-4959-b440-19717918eb6c
  resourceVersion: "219632"
  uid: 3fb22fe8-8fd0-4295-b81f-33def5f2fabd
root@cncf-test4-master:~# 
```

**_2.OauthClient registration is properly updated in mongo_**
```
rs0:PRIMARY> db.OauthClient.find()
{ "_id" : ObjectId("63688ffe68eef85e98544b2e"), "CLIENTID" : "g0jhtxt224e9bvleur8erbygs1ksuv9e", "PROVIDERID" : "Oauth", "CLIENTSECRET" : "{xor}PDktZm8lJzMnZyw3MDw+OC9nPD45bDhvMS8yZ2spNTo=", "DISPLAYNAME" : "g0jhtxt224e9bvleur8erbygs1ksuv9e", "ENABLED" : true, "METADATA" : "{\"client_id_issued_at\":1667796990,\"registration_client_uri\":\"https://platform-auth-service:9443/oidc/endpoint/OP/registration/g0jhtxt224e9bvleur8erbygs1ksuv9e\",\"client_secret_expires_at\":0,\"token_endpoint_auth_method\":\"client_secret_basic\",\"scope\":\"openid profile email\",\"grant_types\":[\"authorization_code\",\"client_credentials\",\"password\",\"implicit\",\"refresh_token\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\"],\"response_types\":[\"code\",\"token\",\"id_token token\"],\"application_type\":\"web\",\"subject_type\":\"public\",\"post_logout_redirect_uris\":[\"https://cp-console.cncf-test4-master.fyre.ibm.com:31573/console/logout\"],\"preauthorized_scope\":\"openid profile email general\",\"introspect_tokens\":true,\"trusted_uri_prefixes\":[\"https://cp-console.cncf-test4-master.fyre.ibm.com:31573/\"],\"resource_ids\":[],\"functional_user_groupIds\":[],\"proofKeyForCodeExchange\":false,\"publicClient\":false,\"appPasswordAllowed\":false,\"appTokenAllowed\":false,\"hash_itr\":0,\"hash_len\":0,\"client_id\":\"g0jhtxt224e9bvleur8erbygs1ksuv9e\",\"client_secret\":\"{xor}PDktZm8lJzMnZyw3MDw+OC9nPD45bDhvMS8yZ2spNTo=\",\"client_name\":\"g0jhtxt224e9bvleur8erbygs1ksuv9e\",\"redirect_uris\":[\"https://cp-console.cncf-test4-master.fyre.ibm.com:31573/auth/liberty/callback\",\"https://127.0.0.1:443/idauth/oidc/endpoint/OP\"],\"allow_regexp_redirects\":false}" }
rs0:PRIMARY> 
```
3.I have tried accessing cp console it is working fine as expected in CNCF cluster
  https://cp-console.cncf-test4-master.fyre.ibm.com:31573

**Review by rashmi43 — APPROVED** [review]

**Review by rashmi43 — APPROVED** [review]
/lgtm

**Pull request merged**
