### PR TITLE
Update csv

### PR DESCRIPTION
**Pull request by znhafeez**
For issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37112, we need to add the `replaces` for upgrade

New CSV already pushed to quay.io and upgrade is functioning

### CODE REVIEW

**Comment by znhafeez** [comment]
@posriniv is this PR ok to merge?

**Comment by posriniv** [comment]
I have removed `replaces` as a part of an issue opened by Adam, we need to confirm with him and can merge. @znhafeez

**Comment by ashank07** [comment]
The replaces section can be present as long as it specifies a valid version, I think this update looks fine.

What breaks our CICD process is if an invalid replaces is specified  (e.g. `replaces: ibm-iam-operator.v0.0.0`), which then breaks our operator-catalog build when that 0.0.0 version can't be found in the CSV package.

**Comment by posriniv** [comment]
@znhafeez please merge it then.

**Comment by znhafeez** [comment]
@posriniv can you add the `/lgmt` label please?

**Pull request merged**
