### PR TITLE
Update ingress.go

### PR DESCRIPTION
**Pull request by smagesh2106**
Add rate limit for issue : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46500

### CODE REVIEW

**Review by rashmi43 — COMMENTED** [review]
please test using hyper foil and share results.

**Comment by smagesh2106** [comment]
@rashmi43 @yannizhang2019 Unless this is merged I cannot test with hyperfoil, let me know otherwise.

**Review by rashmi43 — COMMENTED** [review]
Hey I wanted to set the highest rate limit of 1000 for this one. But is this the one that works?

**Comment by smagesh2106** [comment]
@rashmi43 hyperfoil test results updated in the issue.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46500

**Comment by smagesh2106** [comment]
> 
> 
> Hey I wanted to set the highest rate limit of 1000 for this one. But is this the one that works?

1000 could not be tested successfully , hyperfoil tool itself is throwing null pointer exception and terminating

**Review by rashmi43 — APPROVED** [review]

**Pull request merged**
