### PR TITLE
[CD]ensure roks_url is correct

### PR DESCRIPTION
**Pull request by Tirumalavasa**
This is port from sc2 to CD
that addresses: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62929

### CODE REVIEW

**Comment by Tirumalavasa** [comment]
Test results:

Patched the provider image in my cluster and checked openshift login option is visible
openshift login also works
Restarted the platform-identity-provider pod and rechecked openshift login option is visible and login works

**Comment by Tirumalavasa** [comment]
Screenshot 2024-07-04 at 11 04 27 AM

**Comment by Tirumalavasa** [comment]
Screenshot 2024-07-04 at 11 05 37 AM

**Comment by Tirumalavasa** [comment]
Screenshot 2024-07-04 at 11 06 28 AM

**Comment by ujjwalchk-it** [comment]
@Tirumalavasa Could you pls attach the manual test result?

**Comment by Tirumalavasa** [comment]
@ujjwalchk-it ,Attaching the test results here

Before applying the patch, i have updated ROKS_URL by appending `-testing`
Screenshot 2024-07-09 at 11 24 24 AM

Patched the operator image that has fix and ensured that it is ROKS_URL is updated with right url

Screenshot 2024-07-09 at 11 25 39 AM

**Review by ujjwalchk-it — APPROVED** [review]
LGTM

**Pull request merged**
