### PR TITLE
Clear redundant enpoint idauth

### PR DESCRIPTION
**Pull request by YangShyrMei**
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61141
Parent issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60011

The redundant endpoint "\idauth" is not needed as it redirects to the next endpoint in the route. Therefore, causing an increase in number of security issues.

### CODE REVIEW

**Comment by YangShyrMei** [comment]
Ran regression with this image and the regression was clean with expected failures (which is seen in daily regression as well)
1. regression - 1 failure
2. scim - 2 failures
Attaching results
[idauth - reg .pdf](https://github.com/user-attachments/files/16942627/idauth.-.reg.pdf)
[idauth - scim.pdf](https://github.com/user-attachments/files/16942629/idauth.-.scim.pdf)

**Comment by YangShyrMei** [comment]
Performed manual login testing for LDAP, LDAPS, SAML with SCIM and OIDC.
I tested it in fresh install as well as upgrade scenario where IDPs were previously configured and post upgrade IDPs were intact with login working as expected.
Documented the same in this doc.
[IDAUTH REMOVAL.pdf](https://github.com/user-attachments/files/16942667/IDAUTH.REMOVAL.pdf)

**Review by rwhundley — APPROVED** [review]
/lgtm /approve

**Pull request merged**
